### ISSUE TITLE
Didn't work on Ubuntu 20.04

### ISSUE THREAD

**Issue by JohnAmper** [AmpereComputing/ampere-gcc#1]
I’m not able to use this on UB20.04, seems like I have an OS specific problem.   The ubuntu gcc/g++ does work for me - gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
 
$ pushd ~/ampere-gcc-10.2.1-CentOS-8.2.2004-11923
$ source ./setup_env.sh     
$ popd
 
$ g++ ~/hi.cpp -o /tmp/hi.exe && ldd /tmp/hi.exe
In file included from /home/joneill/ampere-gcc-10.2.1-CentOS-8.2.2004-11923/include/c++/10.2.1/aarch64-unknown-linux-gnu/bits/os_defines.h:39,
                 from /home/joneill/ampere-gcc-10.2.1-CentOS-8.2.2004-11923/include/c++/10.2.1/aarch64-unknown-linux-gnu/bits/c++config.h:522,
                 from /home/joneill/ampere-gcc-10.2.1-CentOS-8.2.2004-11923/include/c++/10.2.1/iostream:38,
                 from /home/joneill/hi.cpp:1:
/usr/include/features.h:461:12: fatal error: sys/cdefs.h: No such file or directory
  461 | #  include <sys/cdefs.h>
      |            ^~~~~~~~~~~~~
compilation terminated.
 
 
$ g++ ~/hi.c -o /tmp/hi.exe && ldd /tmp/hi.exe
In file included from /home/joneill/hi.c:1:
/usr/include/stdio.h:27:10: fatal error: bits/libc-header-start.h: No such file or directory
   27 | #include <bits/libc-header-start.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by jiangning-liu-ampere** [comment]
Sorry, at the moment you can only use Ampere gcc compiler on CentOS/RHEL 8.2/8.3.
